AWSTemplateFormatVersion: "2010-09-09"
Description: Create an AWS Secrets Manager secret with plaintext value and no rotation.

Parameters:
  SecretName:
    Type: String
    Description: Name of the secret to be created.

  PlainTextValue:
    Type: String
    Description: Plaintext value for the secret.3

  Environment:
    Type: String
    Description: environment of the srcret (eg. Production)

Resources:
  Secret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Ref SecretName
      Description: Secret created using CloudFormation.
      SecretString: !Ref PlainTextValue
      Tags:
        - Key: Environment
          Value: !Ref Environment
